// Generated by Selenium IDE
/* 
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class Lab43bookTestTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void lab43bookTest() {
    driver.get("https://cover-bookstore.onrender.com/");
    driver.manage().window().setSize(new Dimension(550, 696));
    driver.findElement(By.cssSelector("div:nth-child(1) > .Navbar_searchBar__3q5Gb > .Navbar_searchBarInput__w8FwI")).click();
    driver.findElement(By.cssSelector("div:nth-child(1) > .Navbar_searchBar__3q5Gb > .Navbar_searchBarInput__w8FwI")).sendKeys("Harry Potter");
    driver.findElement(By.cssSelector("div:nth-child(1) > .Navbar_searchBar__3q5Gb .Navbar_searchBtnIcon__25k0u")).click();
    assertThat(driver.findElement(By.cssSelector(".SearchList_bookTitle__1wo4a")).getText(), is("Harry Potter and the Sorcerer\\\'s Stone"));
    assertThat(driver.findElement(By.cssSelector(".SearchList_bookAuthor__3giPc")).getText(), is("J.K. Rowling"));
  }
}
*/
/* 
import org.junit.jupiter.api.extension.ExtendWith;
import org.openqa.selenium.firefox.FirefoxDriver;
import io.github.bonigarcia.seljup.SeleniumJupiter;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.AfterEach;
import org.openqa.selenium.By;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;
import java.util.*;

import org.junit.jupiter.api.Test;
import static org.hamcrest.MatcherAssert.assertThat; 
import static org.hamcrest.Matchers.*;

@ExtendWith(SeleniumJupiter.class)
public class Lab43bookTest {
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @BeforeEach
  public void setUp() {
    vars = new HashMap<String, Object>();
  }
  @AfterEach
  public void tearDown(FirefoxDriver driver) {
    driver.quit();
  }
  @Test
  public void lab43bookTest(FirefoxDriver driver) {
    driver.get("https://cover-bookstore.onrender.com/");
    driver.manage().window().setSize(new Dimension(550, 696));
    driver.findElement(By.cssSelector("div:nth-child(1) > .Navbar_searchBar__3q5Gb > .Navbar_searchBarInput__w8FwI")).click();
    driver.findElement(By.cssSelector("div:nth-child(1) > .Navbar_searchBar__3q5Gb > .Navbar_searchBarInput__w8FwI")).sendKeys("Harry Potter");
    driver.findElement(By.cssSelector("div:nth-child(1) > .Navbar_searchBar__3q5Gb .Navbar_searchBtnIcon__25k0u")).click();
    assertThat(driver.findElement(By.cssSelector(".SearchList_bookTitle__1wo4a")).getText(), is("Harry Potter and the Sorcerer\'s Stone"));
    assertThat(driver.findElement(By.cssSelector(".SearchList_bookAuthor__3giPc")).getText(), is("J.K. Rowling"));
  }
}
*/